name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Docker Login
    - uses: docker/login-action@v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
           docker build . --file Dockerfile --tag  imagebinarizationflask:$(date +%s)
           docker push smnrao/imagebinarizationflask:lastest



